# Étape 1 : build avec Node
FROM node:20-alpine AS build
WORKDIR /app

# Installer toutes les dépendances
COPY package*.json ./
RUN npm ci

# Copier le reste du code et builder
COPY . .
RUN npm run build

# Étape 2 : servir avec Nginx minimal
FROM nginx:alpine
WORKDIR /usr/share/nginx/html

# Copier uniquement le build final
COPY --from=build /app/dist .

# Config Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
