version: "3.9"
services:
  # Backend
  interpreter:
    build:
      context: ./backend
      dockerfile: Dockerfile_back
    container_name: lang_interpreter
    ports:
      - "5000:5000"
    networks:
      - lang_net

  # Frontend
  ide:
    build:
      context: ./frontend
      dockerfile: Dockerfile_front
    container_name: web_ide
    ports:
      - "8080:80"
    depends_on:
      - interpreter
    networks:
      - lang_net

networks:
  lang_net:
    driver: bridge
