services:
  # --- Backend : interpréteur Python ---
  interpreter:
    build:
      context: ./backend            # Racine du projet
      dockerfile: Dockerfile_back
    container_name: lang_interpreter
    working_dir: /app
    volumes:
      - ./backend:/app          # Monte ton code backend dans /app
    command: python main.py     # Lance ton interpréteur (ou API Flask si tu modifies main.py)
    ports:
      - "5000:5000"             # Expose Flask sur localhost:5000
    networks:
      - lang_net

  # --- Frontend : IDE web avec Nginx ---
  ide:
    build:
      context: ./frontend              # Racine du projet
      dockerfile: Dockerfile_front
    container_name: web_ide
    ports:
      - "8080:80"               # Frontend dispo sur localhost:8080
    volumes:
      - ./frontend:/usr/share/nginx/html  # Sert tes fichiers statiques
    depends_on:
      - interpreter
    networks:
      - lang_net

networks:
  lang_net:
    driver: bridge
