# Étape 1 : image Python légère
FROM python:3.11-slim AS base

WORKDIR /app

# Installer uniquement pip + dépendances système minimales
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Étape 2 : installer dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Étape 3 : copier uniquement les fichiers utiles
COPY app.py lexer.py parser.py interpreter.py ./

# Étape 4 : lancer le serveur
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]
