# Étape 1 : Base Python légère
FROM python:3.11-alpine AS base

# Travailler dans /app
WORKDIR /app

# Installer dépendances système minimales (si certaines libs C en ont besoin)
RUN apk add --no-cache gcc musl-dev libffi-dev

# Copier requirements et installer uniquement le nécessaire
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Étape 2 : Copier seulement les fichiers utiles
COPY app.py lexer.py parser.py interpreter.py ./

# Lancer uvicorn
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]
