name: CD

on:
  push:
    branches:
      - main   # déploiement uniquement sur main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          docker compose down
          docker compose up -d --build
